[supervisord]
nodaemon=true
logfile=/var/www/html/storage/logs/supervisor/supervisord.log
pidfile=/var/www/html/storage/logs/supervisor/supervisord.pid

[program:queue]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:scheduler]
command=/bin/sh -c "while true; do php /var/www/html/artisan schedule:run --no-interaction; sleep 60; done"
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
